import enum


class RiskLevel(enum.StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AgentStatus(enum.StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"


class ExecutionStatus(enum.StrEnum):
    RUNNING = "RUNNING"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"


class ApprovalStatus(enum.StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    EXECUTED = "EXECUTED"


class PaymentStatus(enum.StrEnum):
    SUCCEEDED = "SUCCEEDED"
    REFUNDED = "REFUNDED"


class DeploymentEnvironment(enum.StrEnum):
    STAGING = "STAGING"
    PRODUCTION = "PRODUCTION"


class LogLevel(enum.StrEnum):
    INFO = "INFO"
    WARN = "WARN"
    ERROR = "ERROR"


class AuditEventType(enum.StrEnum):
    EXECUTION_STARTED = "EXECUTION_STARTED"
    AGENT_REASONED = "AGENT_REASONED"
    TOOL_REQUESTED = "TOOL_REQUESTED"
    PERMISSION_CHECKED = "PERMISSION_CHECKED"
    POLICY_CHECKED = "POLICY_CHECKED"
    POLICY_EVALUATION_REQUIRED = "POLICY_EVALUATION_REQUIRED"
    POLICY_EVALUATION_STARTED = "POLICY_EVALUATION_STARTED"
    POLICY_MATCHED = "POLICY_MATCHED"
    POLICY_ALLOWED = "POLICY_ALLOWED"
    POLICY_APPROVAL_REQUIRED = "POLICY_APPROVAL_REQUIRED"
    POLICY_BLOCKED = "POLICY_BLOCKED"
    ACTION_ALLOWED = "ACTION_ALLOWED"
    ACTION_DENIED = "ACTION_DENIED"
    ACTION_BLOCKED = "ACTION_BLOCKED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_APPROVED = "APPROVAL_APPROVED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    APPROVED_ACTION_EXECUTION_STARTED = "APPROVED_ACTION_EXECUTION_STARTED"
    APPROVED_ACTION_EXECUTED = "APPROVED_ACTION_EXECUTED"
    APPROVED_ACTION_FAILED = "APPROVED_ACTION_FAILED"
    RISK_ASSESSMENT_STARTED = "RISK_ASSESSMENT_STARTED"
    RISK_SIGNAL_DETECTED = "RISK_SIGNAL_DETECTED"
    RISK_ASSESSED = "RISK_ASSESSED"
    RISK_ESCALATED = "RISK_ESCALATED"
    ACTION_BLOCKED_BY_RISK = "ACTION_BLOCKED_BY_RISK"
    SECURITY_INCIDENT_CREATED = "SECURITY_INCIDENT_CREATED"
    TOOL_EXECUTED = "TOOL_EXECUTED"
    TOOL_FAILED = "TOOL_FAILED"
    SECURITY_INCIDENT = "SECURITY_INCIDENT"
    EXECUTION_COMPLETED = "EXECUTION_COMPLETED"


class PermissionType(enum.StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    CONDITIONAL = "CONDITIONAL"


class PolicyAction(enum.StrEnum):
    ALLOW = "ALLOW"
    REQUIRE_APPROVAL = "REQUIRE_APPROVAL"
    BLOCK = "BLOCK"


class ToolRequestStatus(enum.StrEnum):
    REQUESTED = "REQUESTED"
    EXECUTED = "EXECUTED"
    DENIED = "DENIED"
    FAILED = "FAILED"
    REQUIRES_APPROVAL = "REQUIRES_APPROVAL"


class IncidentType(enum.StrEnum):
    PROMPT_INJECTION = "PROMPT_INJECTION"
    DATA_EXFILTRATION = "DATA_EXFILTRATION"
    SCOPE_DEVIATION = "SCOPE_DEVIATION"
    SENSITIVE_DATA_ACCESS = "SENSITIVE_DATA_ACCESS"
    PRIVILEGE_ESCALATION = "PRIVILEGE_ESCALATION"
    DESTRUCTIVE_ACTION = "DESTRUCTIVE_ACTION"
    EXTERNAL_COMMUNICATION = "EXTERNAL_COMMUNICATION"
    FINANCIAL_RISK = "FINANCIAL_RISK"
    UNUSUAL_TOOL_SEQUENCE = "UNUSUAL_TOOL_SEQUENCE"


class IncidentStatus(enum.StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    DISMISSED = "DISMISSED"
