"""add production hardening: operators, stepping lease, deploy idempotency

Revision ID: 4e8046c7866f
Revises: d9c633a307e7
Create Date: 2026-09-08 21:05:52.976776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8046c7866f'
down_revision: Union[str, Sequence[str], None] = 'd9c633a307e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('VIEWER', 'OPERATOR', 'APPROVER', 'ADMIN', name='operatorrole', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_role'), 'operators', ['role'], unique=False)
    op.create_index(op.f('ix_operators_username'), 'operators', ['username'], unique=True)
    op.create_table('operator_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_tokens_operator_id'), 'operator_tokens', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_tokens_token_hash'), 'operator_tokens', ['token_hash'], unique=True)
    op.add_column('deployments', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_deployments_idempotency_key'), 'deployments', ['idempotency_key'], unique=True)
    op.add_column('executions', sa.Column('stepping_claim_id', sa.Uuid(), nullable=True))
    op.add_column('executions', sa.Column('stepping_claimed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Not autogenerated: alembic's autogenerate does not reliably diff CHECK
    # constraint value sets on an existing column (same limitation hit in
    # every prior milestone's migration). audit_events.event_type gained one
    # new value used when a terminal-status CAS loses to a prior CANCELLED
    # (see agent_runtime.py::_finalize) -- the audit event must describe
    # what actually happened rather than claim a status transition that did
    # not take effect.
    op.drop_constraint('auditeventtype', 'audit_events', type_='check')
    op.create_check_constraint(
        'auditeventtype',
        'audit_events',
        "event_type IN ("
        "'EXECUTION_STARTED', 'AGENT_REASONED', 'TOOL_REQUESTED', 'PERMISSION_CHECKED', "
        "'POLICY_CHECKED', 'POLICY_EVALUATION_REQUIRED', 'POLICY_EVALUATION_STARTED', "
        "'POLICY_MATCHED', 'POLICY_ALLOWED', 'POLICY_APPROVAL_REQUIRED', 'POLICY_BLOCKED', "
        "'ACTION_ALLOWED', 'ACTION_DENIED', 'ACTION_BLOCKED', "
        "'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', "
        "'APPROVAL_EXPIRED', 'APPROVED_ACTION_EXECUTION_STARTED', 'APPROVED_ACTION_EXECUTED', "
        "'APPROVED_ACTION_FAILED', 'RISK_ASSESSMENT_STARTED', 'RISK_SIGNAL_DETECTED', "
        "'RISK_ASSESSED', 'RISK_ESCALATED', 'ACTION_BLOCKED_BY_RISK', "
        "'SECURITY_INCIDENT_CREATED', 'TOOL_EXECUTED', 'TOOL_FAILED', 'SECURITY_INCIDENT', "
        "'EXECUTION_COMPLETED', 'EXECUTION_STEP_STARTED', 'EXECUTION_STEP_COMPLETED', "
        "'EXECUTION_WAITING_APPROVAL', 'EXECUTION_RESUMED', 'EXECUTION_BLOCKED', "
        "'EXECUTION_FAILED', 'EXECUTION_CANCELLED', 'EXECUTION_STATUS_ALREADY_TERMINAL'"
        ")",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Every row using the new event type is only meaningful together with
    # the lease/idempotency columns this migration adds; same
    # normalize-rather-than-delete-the-Execution pattern as prior
    # milestones (Execution is never cascade-deleted, so we only need to
    # remove the newly-added event rows before narrowing the constraint).
    op.execute(
        "DELETE FROM audit_events WHERE event_type = 'EXECUTION_STATUS_ALREADY_TERMINAL'"
    )
    op.drop_constraint('auditeventtype', 'audit_events', type_='check')
    op.create_check_constraint(
        'auditeventtype',
        'audit_events',
        "event_type IN ("
        "'EXECUTION_STARTED', 'AGENT_REASONED', 'TOOL_REQUESTED', 'PERMISSION_CHECKED', "
        "'POLICY_CHECKED', 'POLICY_EVALUATION_REQUIRED', 'POLICY_EVALUATION_STARTED', "
        "'POLICY_MATCHED', 'POLICY_ALLOWED', 'POLICY_APPROVAL_REQUIRED', 'POLICY_BLOCKED', "
        "'ACTION_ALLOWED', 'ACTION_DENIED', 'ACTION_BLOCKED', "
        "'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', "
        "'APPROVAL_EXPIRED', 'APPROVED_ACTION_EXECUTION_STARTED', 'APPROVED_ACTION_EXECUTED', "
        "'APPROVED_ACTION_FAILED', 'RISK_ASSESSMENT_STARTED', 'RISK_SIGNAL_DETECTED', "
        "'RISK_ASSESSED', 'RISK_ESCALATED', 'ACTION_BLOCKED_BY_RISK', "
        "'SECURITY_INCIDENT_CREATED', 'TOOL_EXECUTED', 'TOOL_FAILED', 'SECURITY_INCIDENT', "
        "'EXECUTION_COMPLETED', 'EXECUTION_STEP_STARTED', 'EXECUTION_STEP_COMPLETED', "
        "'EXECUTION_WAITING_APPROVAL', 'EXECUTION_RESUMED', 'EXECUTION_BLOCKED', "
        "'EXECUTION_FAILED', 'EXECUTION_CANCELLED'"
        ")",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'stepping_claimed_at')
    op.drop_column('executions', 'stepping_claim_id')
    op.drop_index(op.f('ix_deployments_idempotency_key'), table_name='deployments')
    op.drop_column('deployments', 'idempotency_key')
    op.drop_index(op.f('ix_operator_tokens_token_hash'), table_name='operator_tokens')
    op.drop_index(op.f('ix_operator_tokens_operator_id'), table_name='operator_tokens')
    op.drop_table('operator_tokens')
    op.drop_index(op.f('ix_operators_username'), table_name='operators')
    op.drop_index(op.f('ix_operators_role'), table_name='operators')
    op.drop_table('operators')
    # ### end Alembic commands ###
