"""add risk engine and security incidents

Revision ID: 54813d0a7504
Revises: 71b2ebceaf10
Create Date: 2026-09-05 16:33:54.059652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54813d0a7504'
down_revision: Union[str, Sequence[str], None] = '71b2ebceaf10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('tool_request_id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('policy_decision_id', sa.Uuid(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessment_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_action', sa.Enum('ALLOW', 'REQUIRE_APPROVAL', 'BLOCK', name='policyaction', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='ck_risk_assessments_score'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['policy_decision_id'], ['policy_decisions.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['tool_request_id'], ['tool_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_agent_id'), 'risk_assessments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_execution_id'), 'risk_assessments', ['execution_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_policy_decision_id'), 'risk_assessments', ['policy_decision_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_recommended_action'), 'risk_assessments', ['recommended_action'], unique=False)
    op.create_index(op.f('ix_risk_assessments_risk_level'), 'risk_assessments', ['risk_level'], unique=False)
    op.create_index(op.f('ix_risk_assessments_tool_id'), 'risk_assessments', ['tool_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_tool_request_id'), 'risk_assessments', ['tool_request_id'], unique=False)
    op.create_table('security_incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('tool_request_id', sa.Uuid(), nullable=False),
    sa.Column('risk_assessment_id', sa.Uuid(), nullable=False),
    sa.Column('incident_type', sa.Enum('PROMPT_INJECTION', 'DATA_EXFILTRATION', 'SCOPE_DEVIATION', 'SENSITIVE_DATA_ACCESS', 'PRIVILEGE_ESCALATION', 'DESTRUCTIVE_ACTION', 'EXTERNAL_COMMUNICATION', 'FINANCIAL_RISK', 'UNUSUAL_TOOL_SEQUENCE', name='incidenttype', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'DISMISSED', name='incidentstatus', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.ForeignKeyConstraint(['tool_request_id'], ['tool_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_incidents_agent_id'), 'security_incidents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_security_incidents_execution_id'), 'security_incidents', ['execution_id'], unique=False)
    op.create_index(op.f('ix_security_incidents_incident_type'), 'security_incidents', ['incident_type'], unique=False)
    op.create_index(op.f('ix_security_incidents_risk_assessment_id'), 'security_incidents', ['risk_assessment_id'], unique=False)
    op.create_index(op.f('ix_security_incidents_severity'), 'security_incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_security_incidents_status'), 'security_incidents', ['status'], unique=False)
    op.create_index(op.f('ix_security_incidents_tool_request_id'), 'security_incidents', ['tool_request_id'], unique=False)
    # ### end Alembic commands ###

    # Not autogenerated: alembic's autogenerate does not reliably diff CHECK
    # constraint value sets on an existing column (same limitation hit in
    # every prior milestone's migration). audit_events.event_type gained six
    # new values this migration.
    op.drop_constraint('auditeventtype', 'audit_events', type_='check')
    op.create_check_constraint(
        'auditeventtype',
        'audit_events',
        "event_type IN ("
        "'EXECUTION_STARTED', 'AGENT_REASONED', 'TOOL_REQUESTED', 'PERMISSION_CHECKED', "
        "'POLICY_CHECKED', 'POLICY_EVALUATION_REQUIRED', 'POLICY_EVALUATION_STARTED', "
        "'POLICY_MATCHED', 'POLICY_ALLOWED', 'POLICY_APPROVAL_REQUIRED', 'POLICY_BLOCKED', "
        "'ACTION_ALLOWED', 'ACTION_DENIED', 'ACTION_BLOCKED', "
        "'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', "
        "'APPROVAL_EXPIRED', 'APPROVED_ACTION_EXECUTION_STARTED', 'APPROVED_ACTION_EXECUTED', "
        "'APPROVED_ACTION_FAILED', 'RISK_ASSESSMENT_STARTED', 'RISK_SIGNAL_DETECTED', "
        "'RISK_ASSESSED', 'RISK_ESCALATED', 'ACTION_BLOCKED_BY_RISK', "
        "'SECURITY_INCIDENT_CREATED', 'TOOL_EXECUTED', 'TOOL_FAILED', 'SECURITY_INCIDENT', "
        "'EXECUTION_COMPLETED'"
        ")",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Every row referencing one of the six new event types is only
    # meaningful together with the risk_assessments/security_incidents
    # tables this migration adds. Drop them before narrowing the CHECK
    # constraint back, same pattern as the milestone 6 approval downgrade.
    op.execute(
        "DELETE FROM audit_events WHERE event_type IN ("
        "'RISK_ASSESSMENT_STARTED', 'RISK_SIGNAL_DETECTED', 'RISK_ESCALATED', "
        "'ACTION_BLOCKED_BY_RISK', 'SECURITY_INCIDENT_CREATED')"
    )
    op.drop_constraint('auditeventtype', 'audit_events', type_='check')
    op.create_check_constraint(
        'auditeventtype',
        'audit_events',
        "event_type IN ("
        "'EXECUTION_STARTED', 'AGENT_REASONED', 'TOOL_REQUESTED', 'PERMISSION_CHECKED', "
        "'POLICY_CHECKED', 'POLICY_EVALUATION_REQUIRED', 'POLICY_EVALUATION_STARTED', "
        "'POLICY_MATCHED', 'POLICY_ALLOWED', 'POLICY_APPROVAL_REQUIRED', 'POLICY_BLOCKED', "
        "'RISK_ASSESSED', 'ACTION_ALLOWED', 'ACTION_DENIED', 'ACTION_BLOCKED', "
        "'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', "
        "'APPROVAL_EXPIRED', 'APPROVED_ACTION_EXECUTION_STARTED', 'APPROVED_ACTION_EXECUTED', "
        "'APPROVED_ACTION_FAILED', 'TOOL_EXECUTED', 'TOOL_FAILED', 'SECURITY_INCIDENT', "
        "'EXECUTION_COMPLETED'"
        ")",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_incidents_tool_request_id'), table_name='security_incidents')
    op.drop_index(op.f('ix_security_incidents_status'), table_name='security_incidents')
    op.drop_index(op.f('ix_security_incidents_severity'), table_name='security_incidents')
    op.drop_index(op.f('ix_security_incidents_risk_assessment_id'), table_name='security_incidents')
    op.drop_index(op.f('ix_security_incidents_incident_type'), table_name='security_incidents')
    op.drop_index(op.f('ix_security_incidents_execution_id'), table_name='security_incidents')
    op.drop_index(op.f('ix_security_incidents_agent_id'), table_name='security_incidents')
    op.drop_table('security_incidents')
    op.drop_index(op.f('ix_risk_assessments_tool_request_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_tool_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_level'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_recommended_action'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_policy_decision_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_execution_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_agent_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
