"""add external agent integration layer: principals, scopes, agent mapping, external action requests

Revision ID: 5e1b934b398f
Revises: 4e8046c7866f
Create Date: 2026-09-08 23:05:18.077775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e1b934b398f'
down_revision: Union[str, Sequence[str], None] = '4e8046c7866f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_agent_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'agent_id', name='uq_integration_agent_mapping')
    )
    op.create_index(op.f('ix_integration_agent_mappings_agent_id'), 'integration_agent_mappings', ['agent_id'], unique=False)
    op.create_index(op.f('ix_integration_agent_mappings_operator_id'), 'integration_agent_mappings', ['operator_id'], unique=False)
    op.create_table('external_action_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('integration_type', sa.Enum('GENERIC', 'MCP', name='integrationtype', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('external_request_id', sa.String(length=255), nullable=False),
    sa.Column('external_agent_id', sa.String(length=255), nullable=True),
    sa.Column('safeops_agent_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('tool_request_id', sa.Uuid(), nullable=True),
    sa.Column('approval_request_id', sa.Uuid(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'VALIDATED', 'PROCESSING', 'WAITING_APPROVAL', 'EXECUTED', 'BLOCKED', 'FAILED', name='externalactionstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['safeops_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tool_request_id'], ['tool_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operator_id', 'external_request_id', name='uq_external_action_request_idempotency')
    )
    op.create_index(op.f('ix_external_action_requests_execution_id'), 'external_action_requests', ['execution_id'], unique=False)
    op.create_index(op.f('ix_external_action_requests_external_request_id'), 'external_action_requests', ['external_request_id'], unique=False)
    op.create_index(op.f('ix_external_action_requests_operator_id'), 'external_action_requests', ['operator_id'], unique=False)
    op.create_index(op.f('ix_external_action_requests_payload_hash'), 'external_action_requests', ['payload_hash'], unique=False)
    op.create_index(op.f('ix_external_action_requests_safeops_agent_id'), 'external_action_requests', ['safeops_agent_id'], unique=False)
    op.create_index(op.f('ix_external_action_requests_status'), 'external_action_requests', ['status'], unique=False)
    # ### end Alembic commands ###

    # Not autogenerated: added nullable first and backfilled so existing
    # `operators` rows (every seeded demo operator from Milestone 10) don't
    # violate a NOT NULL constraint with no default -- same pattern as the
    # milestone 8/9 backfills.
    op.add_column(
        'operators',
        sa.Column('principal_type', sa.Enum('OPERATOR', 'INTEGRATION', name='principaltype', native_enum=False, create_constraint=True, length=16), nullable=True),
    )
    op.execute("UPDATE operators SET principal_type = 'OPERATOR' WHERE principal_type IS NULL")
    op.alter_column('operators', 'principal_type', nullable=False)
    op.create_index(op.f('ix_operators_principal_type'), 'operators', ['principal_type'], unique=False)

    op.add_column(
        'operators', sa.Column('integration_scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.execute("UPDATE operators SET integration_scopes = '[]'::jsonb WHERE integration_scopes IS NULL")
    op.alter_column('operators', 'integration_scopes', nullable=False)

    # Not autogenerated: alembic's autogenerate does not reliably diff CHECK
    # constraint value sets on an existing column (same limitation hit in
    # every prior milestone's migration). audit_events.event_type gained six
    # new values for the external-agent integration audit trail.
    op.drop_constraint('auditeventtype', 'audit_events', type_='check')
    op.create_check_constraint(
        'auditeventtype',
        'audit_events',
        "event_type IN ("
        "'EXECUTION_STARTED', 'AGENT_REASONED', 'TOOL_REQUESTED', 'PERMISSION_CHECKED', "
        "'POLICY_CHECKED', 'POLICY_EVALUATION_REQUIRED', 'POLICY_EVALUATION_STARTED', "
        "'POLICY_MATCHED', 'POLICY_ALLOWED', 'POLICY_APPROVAL_REQUIRED', 'POLICY_BLOCKED', "
        "'ACTION_ALLOWED', 'ACTION_DENIED', 'ACTION_BLOCKED', "
        "'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', "
        "'APPROVAL_EXPIRED', 'APPROVED_ACTION_EXECUTION_STARTED', 'APPROVED_ACTION_EXECUTED', "
        "'APPROVED_ACTION_FAILED', 'RISK_ASSESSMENT_STARTED', 'RISK_SIGNAL_DETECTED', "
        "'RISK_ASSESSED', 'RISK_ESCALATED', 'ACTION_BLOCKED_BY_RISK', "
        "'SECURITY_INCIDENT_CREATED', 'TOOL_EXECUTED', 'TOOL_FAILED', 'SECURITY_INCIDENT', "
        "'EXECUTION_COMPLETED', 'EXECUTION_STEP_STARTED', 'EXECUTION_STEP_COMPLETED', "
        "'EXECUTION_WAITING_APPROVAL', 'EXECUTION_RESUMED', 'EXECUTION_BLOCKED', "
        "'EXECUTION_FAILED', 'EXECUTION_CANCELLED', 'EXECUTION_STATUS_ALREADY_TERMINAL', "
        "'EXTERNAL_REQUEST_RECEIVED', 'EXTERNAL_REQUEST_VALIDATED', 'EXTERNAL_REQUEST_REJECTED', "
        "'EXTERNAL_ACTION_SUBMITTED', 'EXTERNAL_ACTION_WAITING_APPROVAL', "
        "'EXTERNAL_ACTION_COMPLETED'"
        ")",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Every row using one of the six new event types is only meaningful
    # together with the tables/columns this migration adds -- same
    # normalize-rather-than-delete-the-Execution pattern as prior
    # milestones (Execution/Operator are never cascade-deleted, so we only
    # need to remove the newly-added audit rows before narrowing the
    # constraint back).
    op.execute(
        "DELETE FROM audit_events WHERE event_type IN ("
        "'EXTERNAL_REQUEST_RECEIVED', 'EXTERNAL_REQUEST_VALIDATED', 'EXTERNAL_REQUEST_REJECTED', "
        "'EXTERNAL_ACTION_SUBMITTED', 'EXTERNAL_ACTION_WAITING_APPROVAL', "
        "'EXTERNAL_ACTION_COMPLETED')"
    )
    op.drop_constraint('auditeventtype', 'audit_events', type_='check')
    op.create_check_constraint(
        'auditeventtype',
        'audit_events',
        "event_type IN ("
        "'EXECUTION_STARTED', 'AGENT_REASONED', 'TOOL_REQUESTED', 'PERMISSION_CHECKED', "
        "'POLICY_CHECKED', 'POLICY_EVALUATION_REQUIRED', 'POLICY_EVALUATION_STARTED', "
        "'POLICY_MATCHED', 'POLICY_ALLOWED', 'POLICY_APPROVAL_REQUIRED', 'POLICY_BLOCKED', "
        "'ACTION_ALLOWED', 'ACTION_DENIED', 'ACTION_BLOCKED', "
        "'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', "
        "'APPROVAL_EXPIRED', 'APPROVED_ACTION_EXECUTION_STARTED', 'APPROVED_ACTION_EXECUTED', "
        "'APPROVED_ACTION_FAILED', 'RISK_ASSESSMENT_STARTED', 'RISK_SIGNAL_DETECTED', "
        "'RISK_ASSESSED', 'RISK_ESCALATED', 'ACTION_BLOCKED_BY_RISK', "
        "'SECURITY_INCIDENT_CREATED', 'TOOL_EXECUTED', 'TOOL_FAILED', 'SECURITY_INCIDENT', "
        "'EXECUTION_COMPLETED', 'EXECUTION_STEP_STARTED', 'EXECUTION_STEP_COMPLETED', "
        "'EXECUTION_WAITING_APPROVAL', 'EXECUTION_RESUMED', 'EXECUTION_BLOCKED', "
        "'EXECUTION_FAILED', 'EXECUTION_CANCELLED', 'EXECUTION_STATUS_ALREADY_TERMINAL'"
        ")",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operators_principal_type'), table_name='operators')
    op.drop_column('operators', 'integration_scopes')
    op.drop_column('operators', 'principal_type')
    op.drop_index(op.f('ix_external_action_requests_status'), table_name='external_action_requests')
    op.drop_index(op.f('ix_external_action_requests_safeops_agent_id'), table_name='external_action_requests')
    op.drop_index(op.f('ix_external_action_requests_payload_hash'), table_name='external_action_requests')
    op.drop_index(op.f('ix_external_action_requests_operator_id'), table_name='external_action_requests')
    op.drop_index(op.f('ix_external_action_requests_external_request_id'), table_name='external_action_requests')
    op.drop_index(op.f('ix_external_action_requests_execution_id'), table_name='external_action_requests')
    op.drop_table('external_action_requests')
    op.drop_index(op.f('ix_integration_agent_mappings_operator_id'), table_name='integration_agent_mappings')
    op.drop_index(op.f('ix_integration_agent_mappings_agent_id'), table_name='integration_agent_mappings')
    op.drop_table('integration_agent_mappings')
    # ### end Alembic commands ###
