"""add approval engine

Revision ID: 71b2ebceaf10
Revises: 92c9d30a5b8d
Create Date: 2026-09-05 13:27:45.498334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71b2ebceaf10'
down_revision: Union[str, Sequence[str], None] = '92c9d30a5b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('tool_request_id', sa.Uuid(), nullable=False))
    op.add_column('approval_requests', sa.Column('policy_decision_id', sa.Uuid(), nullable=False))
    op.add_column('approval_requests', sa.Column('approved_arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('approval_requests', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('approval_requests', sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_approval_requests_policy_decision_id'), 'approval_requests', ['policy_decision_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_tool_request_id'), 'approval_requests', ['tool_request_id'], unique=False)
    op.create_foreign_key(
        'approval_requests_policy_decision_id_fkey',
        'approval_requests',
        'policy_decisions',
        ['policy_decision_id'],
        ['id'],
    )
    op.create_foreign_key(
        'approval_requests_tool_request_id_fkey',
        'approval_requests',
        'tool_requests',
        ['tool_request_id'],
        ['id'],
    )
    op.drop_column('approval_requests', 'arguments')
    op.alter_column('audit_events', 'event_type',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###

    # Not autogenerated: alembic's autogenerate does not reliably diff CHECK
    # constraint value sets on an existing column (same limitation hit in the
    # milestone 4 and milestone 5 migrations). Both auditeventtype and
    # approvalstatus gained new values this migration.
    op.drop_constraint('auditeventtype', 'audit_events', type_='check')
    op.create_check_constraint(
        'auditeventtype',
        'audit_events',
        "event_type IN ("
        "'EXECUTION_STARTED', 'AGENT_REASONED', 'TOOL_REQUESTED', 'PERMISSION_CHECKED', "
        "'POLICY_CHECKED', 'POLICY_EVALUATION_REQUIRED', 'POLICY_EVALUATION_STARTED', "
        "'POLICY_MATCHED', 'POLICY_ALLOWED', 'POLICY_APPROVAL_REQUIRED', 'POLICY_BLOCKED', "
        "'RISK_ASSESSED', 'ACTION_ALLOWED', 'ACTION_DENIED', 'ACTION_BLOCKED', "
        "'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', "
        "'APPROVAL_EXPIRED', 'APPROVED_ACTION_EXECUTION_STARTED', 'APPROVED_ACTION_EXECUTED', "
        "'APPROVED_ACTION_FAILED', 'TOOL_EXECUTED', 'TOOL_FAILED', 'SECURITY_INCIDENT', "
        "'EXECUTION_COMPLETED'"
        ")",
    )
    op.drop_constraint('approvalstatus', 'approval_requests', type_='check')
    op.create_check_constraint(
        'approvalstatus',
        'approval_requests',
        "status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', 'EXECUTED')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # approval_requests had zero rows before this migration (the table
    # existed but was never populated pre-milestone-6), and every row that
    # exists at downgrade time is only meaningful together with the
    # tool_request_id/policy_decision_id/approved_arguments/expires_at
    # columns this migration adds -- there is no way to preserve a row
    # without them that a later re-upgrade could safely NOT NULL again. So
    # rather than partially preserving rows (e.g. EXECUTED -> APPROVED) and
    # leaving the new columns unbackfillable on re-upgrade, downgrade drops
    # all approval_requests rows outright, same as the audit events that
    # reference milestone-6-only event types.
    op.execute(
        "DELETE FROM audit_events WHERE event_type IN ("
        "'APPROVAL_APPROVED', 'APPROVAL_REJECTED', 'APPROVAL_EXPIRED', "
        "'APPROVED_ACTION_EXECUTION_STARTED', 'APPROVED_ACTION_EXECUTED', "
        "'APPROVED_ACTION_FAILED')"
    )
    op.execute("DELETE FROM approval_requests")

    op.drop_constraint('approvalstatus', 'approval_requests', type_='check')
    op.create_check_constraint(
        'approvalstatus',
        'approval_requests',
        "status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED')",
    )
    op.drop_constraint('auditeventtype', 'audit_events', type_='check')
    op.create_check_constraint(
        'auditeventtype',
        'audit_events',
        "event_type IN ("
        "'EXECUTION_STARTED', 'AGENT_REASONED', 'TOOL_REQUESTED', 'PERMISSION_CHECKED', "
        "'POLICY_CHECKED', 'POLICY_EVALUATION_REQUIRED', 'POLICY_EVALUATION_STARTED', "
        "'POLICY_MATCHED', 'POLICY_ALLOWED', 'POLICY_APPROVAL_REQUIRED', 'POLICY_BLOCKED', "
        "'RISK_ASSESSED', 'ACTION_ALLOWED', 'ACTION_DENIED', 'ACTION_BLOCKED', "
        "'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'TOOL_EXECUTED', 'TOOL_FAILED', "
        "'SECURITY_INCIDENT', 'EXECUTION_COMPLETED'"
        ")",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_events', 'event_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # Re-added nullable first and backfilled from approved_arguments (any
    # existing rows), then tightened to NOT NULL -- the auto-generated
    # nullable=False add_column would crash outright if rows exist.
    op.add_column(
        'approval_requests',
        sa.Column(
            'arguments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
    )
    op.execute("UPDATE approval_requests SET arguments = approved_arguments")
    op.alter_column('approval_requests', 'arguments', nullable=False)
    op.drop_constraint(
        'approval_requests_policy_decision_id_fkey', 'approval_requests', type_='foreignkey'
    )
    op.drop_constraint(
        'approval_requests_tool_request_id_fkey', 'approval_requests', type_='foreignkey'
    )
    op.drop_index(op.f('ix_approval_requests_tool_request_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_policy_decision_id'), table_name='approval_requests')
    op.drop_column('approval_requests', 'executed_at')
    op.drop_column('approval_requests', 'expires_at')
    op.drop_column('approval_requests', 'approved_arguments')
    op.drop_column('approval_requests', 'policy_decision_id')
    op.drop_column('approval_requests', 'tool_request_id')
    # ### end Alembic commands ###
