"""add tool gateway permissions and requests

Revision ID: 81fe3a3e220c
Revises: c7fbc39f5bf9
Create Date: 2026-09-04 22:04:07.529387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81fe3a3e220c'
down_revision: Union[str, Sequence[str], None] = 'c7fbc39f5bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_tool_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.Enum('ALLOW', 'DENY', 'CONDITIONAL', name='permissiontype', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'tool_id', name='uq_agent_tool_permissions_agent_tool')
    )
    op.create_index(op.f('ix_agent_tool_permissions_agent_id'), 'agent_tool_permissions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_permissions_permission'), 'agent_tool_permissions', ['permission'], unique=False)
    op.create_index(op.f('ix_agent_tool_permissions_tool_id'), 'agent_tool_permissions', ['tool_id'], unique=False)
    op.create_table('tool_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'EXECUTED', 'DENIED', 'FAILED', name='toolrequeststatus', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_requests_agent_id'), 'tool_requests', ['agent_id'], unique=False)
    op.create_index(op.f('ix_tool_requests_execution_id'), 'tool_requests', ['execution_id'], unique=False)
    op.create_index(op.f('ix_tool_requests_status'), 'tool_requests', ['status'], unique=False)
    op.create_index(op.f('ix_tool_requests_tool_id'), 'tool_requests', ['tool_id'], unique=False)
    op.create_index(op.f('ix_tool_requests_tool_name'), 'tool_requests', ['tool_name'], unique=False)
    # ### end Alembic commands ###

    # Not autogenerated: alembic's autogenerate does not reliably diff CHECK
    # constraint value sets on an existing column. AuditEventType gained
    # PERMISSION_CHECKED, ACTION_DENIED, and POLICY_EVALUATION_REQUIRED.
    op.drop_constraint('auditeventtype', 'audit_events', type_='check')
    op.create_check_constraint(
        'auditeventtype',
        'audit_events',
        "event_type IN ("
        "'EXECUTION_STARTED', 'AGENT_REASONED', 'TOOL_REQUESTED', 'PERMISSION_CHECKED', "
        "'POLICY_CHECKED', 'POLICY_EVALUATION_REQUIRED', 'RISK_ASSESSED', 'ACTION_ALLOWED', "
        "'ACTION_DENIED', 'ACTION_BLOCKED', 'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', "
        "'TOOL_EXECUTED', 'TOOL_FAILED', 'SECURITY_INCIDENT', 'EXECUTION_COMPLETED'"
        ")",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('auditeventtype', 'audit_events', type_='check')
    op.create_check_constraint(
        'auditeventtype',
        'audit_events',
        "event_type IN ("
        "'EXECUTION_STARTED', 'AGENT_REASONED', 'TOOL_REQUESTED', 'POLICY_CHECKED', "
        "'RISK_ASSESSED', 'ACTION_ALLOWED', 'ACTION_BLOCKED', 'APPROVAL_REQUESTED', "
        "'APPROVAL_GRANTED', 'TOOL_EXECUTED', 'TOOL_FAILED', 'SECURITY_INCIDENT', "
        "'EXECUTION_COMPLETED'"
        ")",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_requests_tool_name'), table_name='tool_requests')
    op.drop_index(op.f('ix_tool_requests_tool_id'), table_name='tool_requests')
    op.drop_index(op.f('ix_tool_requests_status'), table_name='tool_requests')
    op.drop_index(op.f('ix_tool_requests_execution_id'), table_name='tool_requests')
    op.drop_index(op.f('ix_tool_requests_agent_id'), table_name='tool_requests')
    op.drop_table('tool_requests')
    op.drop_index(op.f('ix_agent_tool_permissions_tool_id'), table_name='agent_tool_permissions')
    op.drop_index(op.f('ix_agent_tool_permissions_permission'), table_name='agent_tool_permissions')
    op.drop_index(op.f('ix_agent_tool_permissions_agent_id'), table_name='agent_tool_permissions')
    op.drop_table('agent_tool_permissions')
    # ### end Alembic commands ###
