"""add policy engine

Revision ID: 92c9d30a5b8d
Revises: 81fe3a3e220c
Create Date: 2026-09-04 22:44:37.360777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92c9d30a5b8d'
down_revision: Union[str, Sequence[str], None] = '81fe3a3e220c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('policy_key', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('tool_id', sa.Uuid(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('action', sa.Enum('ALLOW', 'REQUIRE_APPROVAL', 'BLOCK', name='policyaction', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_key', name='uq_policies_policy_key')
    )
    op.create_index(op.f('ix_policies_action'), 'policies', ['action'], unique=False)
    op.create_index(op.f('ix_policies_agent_id'), 'policies', ['agent_id'], unique=False)
    op.create_index(op.f('ix_policies_agent_type'), 'policies', ['agent_type'], unique=False)
    op.create_index(op.f('ix_policies_policy_key'), 'policies', ['policy_key'], unique=False)
    op.create_index(op.f('ix_policies_tool_id'), 'policies', ['tool_id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('tool_request_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('ALLOW', 'REQUIRE_APPROVAL', 'BLOCK', name='policyaction', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('matched_policy_id', sa.Uuid(), nullable=True),
    sa.Column('matched_policy_key', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=2000), nullable=False),
    sa.Column('evaluated_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['matched_policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['tool_request_id'], ['tool_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_agent_id'), 'policy_decisions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_decision'), 'policy_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_policy_decisions_execution_id'), 'policy_decisions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_matched_policy_id'), 'policy_decisions', ['matched_policy_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_tool_id'), 'policy_decisions', ['tool_id'], unique=False)
    op.create_index(op.f('ix_policy_decisions_tool_request_id'), 'policy_decisions', ['tool_request_id'], unique=False)
    op.alter_column('tool_requests', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###

    # Not autogenerated: autogenerate does not reliably diff CHECK constraint
    # value sets on an existing column (see the 81fe3a3e220c migration). Also,
    # `type_=` on alter_column is deliberately a plain String above (not the
    # Enum), because passing the Enum there makes SQLAlchemy try to attach its
    # own same-named CHECK constraint as a side effect of the type change,
    # colliding with the explicit drop/create below.
    # ToolRequestStatus gained REQUIRES_APPROVAL; AuditEventType gained the
    # five POLICY_* evaluation events.
    op.drop_constraint('toolrequeststatus', 'tool_requests', type_='check')
    op.create_check_constraint(
        'toolrequeststatus',
        'tool_requests',
        "status IN ('REQUESTED', 'EXECUTED', 'DENIED', 'FAILED', 'REQUIRES_APPROVAL')",
    )

    op.drop_constraint('auditeventtype', 'audit_events', type_='check')
    op.create_check_constraint(
        'auditeventtype',
        'audit_events',
        "event_type IN ("
        "'EXECUTION_STARTED', 'AGENT_REASONED', 'TOOL_REQUESTED', 'PERMISSION_CHECKED', "
        "'POLICY_CHECKED', 'POLICY_EVALUATION_REQUIRED', 'POLICY_EVALUATION_STARTED', "
        "'POLICY_MATCHED', 'POLICY_ALLOWED', 'POLICY_APPROVAL_REQUIRED', 'POLICY_BLOCKED', "
        "'RISK_ASSESSED', 'ACTION_ALLOWED', 'ACTION_DENIED', 'ACTION_BLOCKED', "
        "'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'TOOL_EXECUTED', 'TOOL_FAILED', "
        "'SECURITY_INCIDENT', 'EXECUTION_COMPLETED'"
        ")",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('auditeventtype', 'audit_events', type_='check')
    op.create_check_constraint(
        'auditeventtype',
        'audit_events',
        "event_type IN ("
        "'EXECUTION_STARTED', 'AGENT_REASONED', 'TOOL_REQUESTED', 'PERMISSION_CHECKED', "
        "'POLICY_CHECKED', 'POLICY_EVALUATION_REQUIRED', 'RISK_ASSESSED', 'ACTION_ALLOWED', "
        "'ACTION_DENIED', 'ACTION_BLOCKED', 'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', "
        "'TOOL_EXECUTED', 'TOOL_FAILED', 'SECURITY_INCIDENT', 'EXECUTION_COMPLETED'"
        ")",
    )

    op.drop_constraint('toolrequeststatus', 'tool_requests', type_='check')
    op.create_check_constraint(
        'toolrequeststatus',
        'tool_requests',
        "status IN ('REQUESTED', 'EXECUTED', 'DENIED', 'FAILED')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tool_requests', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_index(op.f('ix_policy_decisions_tool_request_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_tool_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_matched_policy_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_execution_id'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_decision'), table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_agent_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_policies_tool_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_policy_key'), table_name='policies')
    op.drop_index(op.f('ix_policies_agent_type'), table_name='policies')
    op.drop_index(op.f('ix_policies_agent_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_action'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
