"""add agent runtime execution steps

Revision ID: d9c633a307e7
Revises: 54813d0a7504
Create Date: 2026-09-06 14:19:23.696201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9c633a307e7'
down_revision: Union[str, Sequence[str], None] = '54813d0a7504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.Enum('PLAN', 'TOOL_CALL', 'TOOL_RESULT', 'APPROVAL_WAIT', 'FINAL', name='steptype', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('tool_request_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'WAITING_APPROVAL', 'BLOCKED', 'FAILED', name='stepstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.ForeignKeyConstraint(['tool_request_id'], ['tool_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'sequence', name='uq_execution_steps_execution_sequence')
    )
    op.create_index(op.f('ix_execution_steps_execution_id'), 'execution_steps', ['execution_id'], unique=False)
    op.create_index(op.f('ix_execution_steps_status'), 'execution_steps', ['status'], unique=False)
    op.create_index(op.f('ix_execution_steps_step_type'), 'execution_steps', ['step_type'], unique=False)
    op.create_index(op.f('ix_execution_steps_tool_request_id'), 'execution_steps', ['tool_request_id'], unique=False)
    # ### end Alembic commands ###

    # Not autogenerated: added nullable first and backfilled so existing
    # `executions` rows (there are some, from milestones 1-7) don't violate
    # a NOT NULL constraint with no default, then tightened to NOT NULL --
    # same pattern as the milestone 6 approval_requests.arguments backfill.
    op.add_column(
        'executions',
        sa.Column('initial_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.execute("UPDATE executions SET initial_context = '{}'::jsonb WHERE initial_context IS NULL")
    op.alter_column('executions', 'initial_context', nullable=False)

    # Non-blocking claim flag AgentRuntime.step()/resume() use to serialize
    # the whole plan-execute-finalize critical section per execution (see
    # app/services/agent_runtime.py for why this is plain row data rather
    # than a Postgres advisory lock). Existing rows default to false/unclaimed.
    op.add_column(
        'executions',
        sa.Column('stepping', sa.Boolean(), nullable=True),
    )
    op.execute("UPDATE executions SET stepping = false WHERE stepping IS NULL")
    op.alter_column('executions', 'stepping', nullable=False)

    # Not autogenerated: alembic's autogenerate does not reliably diff CHECK
    # constraint value sets on an existing column (same limitation hit in
    # every prior milestone's migration). executions.status gained CREATED
    # and CANCELLED, and audit_events.event_type gained seven new values.
    op.drop_constraint('executionstatus', 'executions', type_='check')
    op.create_check_constraint(
        'executionstatus',
        'executions',
        "status IN ('CREATED', 'RUNNING', 'WAITING_APPROVAL', 'COMPLETED', 'FAILED', "
        "'BLOCKED', 'CANCELLED')",
    )
    op.drop_constraint('auditeventtype', 'audit_events', type_='check')
    op.create_check_constraint(
        'auditeventtype',
        'audit_events',
        "event_type IN ("
        "'EXECUTION_STARTED', 'AGENT_REASONED', 'TOOL_REQUESTED', 'PERMISSION_CHECKED', "
        "'POLICY_CHECKED', 'POLICY_EVALUATION_REQUIRED', 'POLICY_EVALUATION_STARTED', "
        "'POLICY_MATCHED', 'POLICY_ALLOWED', 'POLICY_APPROVAL_REQUIRED', 'POLICY_BLOCKED', "
        "'ACTION_ALLOWED', 'ACTION_DENIED', 'ACTION_BLOCKED', "
        "'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', "
        "'APPROVAL_EXPIRED', 'APPROVED_ACTION_EXECUTION_STARTED', 'APPROVED_ACTION_EXECUTED', "
        "'APPROVED_ACTION_FAILED', 'RISK_ASSESSMENT_STARTED', 'RISK_SIGNAL_DETECTED', "
        "'RISK_ASSESSED', 'RISK_ESCALATED', 'ACTION_BLOCKED_BY_RISK', "
        "'SECURITY_INCIDENT_CREATED', 'TOOL_EXECUTED', 'TOOL_FAILED', 'SECURITY_INCIDENT', "
        "'EXECUTION_COMPLETED', 'EXECUTION_STEP_STARTED', 'EXECUTION_STEP_COMPLETED', "
        "'EXECUTION_WAITING_APPROVAL', 'EXECUTION_RESUMED', 'EXECUTION_BLOCKED', "
        "'EXECUTION_FAILED', 'EXECUTION_CANCELLED'"
        ")",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Every row referencing one of the seven new event types, or an
    # execution sitting in CREATED/CANCELLED, is only meaningful together
    # with the execution_steps table and columns this migration adds. Drop
    # them before narrowing the CHECK constraints back, same pattern as the
    # milestone 6/7 downgrades.
    op.execute(
        "DELETE FROM audit_events WHERE event_type IN ("
        "'EXECUTION_STEP_STARTED', 'EXECUTION_STEP_COMPLETED', "
        "'EXECUTION_WAITING_APPROVAL', 'EXECUTION_RESUMED', 'EXECUTION_BLOCKED', "
        "'EXECUTION_FAILED', 'EXECUTION_CANCELLED')"
    )
    # Normalize rather than delete: an Execution is the parent of many other
    # tables (tool_requests, policy_decisions, risk_assessments,
    # security_incidents, approval_requests, its own audit_events), and none
    # of those are cascade-deleted by design (see milestone 2). Deleting the
    # Execution row itself would either violate those FK constraints or
    # destroy unrelated history; remapping the status value to the nearest
    # pre-milestone-8 equivalent keeps everything else intact.
    op.execute("UPDATE executions SET status = 'RUNNING' WHERE status = 'CREATED'")
    op.execute("UPDATE executions SET status = 'FAILED' WHERE status = 'CANCELLED'")
    op.drop_constraint('auditeventtype', 'audit_events', type_='check')
    op.create_check_constraint(
        'auditeventtype',
        'audit_events',
        "event_type IN ("
        "'EXECUTION_STARTED', 'AGENT_REASONED', 'TOOL_REQUESTED', 'PERMISSION_CHECKED', "
        "'POLICY_CHECKED', 'POLICY_EVALUATION_REQUIRED', 'POLICY_EVALUATION_STARTED', "
        "'POLICY_MATCHED', 'POLICY_ALLOWED', 'POLICY_APPROVAL_REQUIRED', 'POLICY_BLOCKED', "
        "'ACTION_ALLOWED', 'ACTION_DENIED', 'ACTION_BLOCKED', "
        "'APPROVAL_REQUESTED', 'APPROVAL_GRANTED', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', "
        "'APPROVAL_EXPIRED', 'APPROVED_ACTION_EXECUTION_STARTED', 'APPROVED_ACTION_EXECUTED', "
        "'APPROVED_ACTION_FAILED', 'RISK_ASSESSMENT_STARTED', 'RISK_SIGNAL_DETECTED', "
        "'RISK_ASSESSED', 'RISK_ESCALATED', 'ACTION_BLOCKED_BY_RISK', "
        "'SECURITY_INCIDENT_CREATED', 'TOOL_EXECUTED', 'TOOL_FAILED', 'SECURITY_INCIDENT', "
        "'EXECUTION_COMPLETED'"
        ")",
    )
    op.drop_constraint('executionstatus', 'executions', type_='check')
    op.create_check_constraint(
        'executionstatus',
        'executions',
        "status IN ('RUNNING', 'WAITING_APPROVAL', 'COMPLETED', 'FAILED', 'BLOCKED')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executions', 'stepping')
    op.drop_column('executions', 'initial_context')
    op.drop_index(op.f('ix_execution_steps_tool_request_id'), table_name='execution_steps')
    op.drop_index(op.f('ix_execution_steps_step_type'), table_name='execution_steps')
    op.drop_index(op.f('ix_execution_steps_status'), table_name='execution_steps')
    op.drop_index(op.f('ix_execution_steps_execution_id'), table_name='execution_steps')
    op.drop_table('execution_steps')
    # ### end Alembic commands ###
